### ISSUE TITLE
V1.2.5的两处报错

### ISSUE THREAD

**Issue by xxsmile123** [Soufaker/laoyue#21]
基础V1.2.5最新版本，填了目标以后运行产生的报错。
报错1：
报错位置：
naabu运行附近。
报错内容：
['./result/ip_as_domain/xxx.com.cn.txt', './result/ip_as_domain/1.txt', './result/ip_as_domain/temp_ip.txt']
./result/ip_as_domain/xxx.com.cn.txt
./result/maindomain/xxx.com.cn.txt
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
java -jar ./inifile/hostscan/HostCollision.jar -ifp ./result/ip_as_domain/xxx.com.cn.txt -hfp ./result/maindomain/xxx.com.cn.txt -t 10 -cssc 200 &gt; ./inifile/hostscan/2024-01-30-21-51-19_host_scan.txt
./result/ip_as_domain/1.txt
./result/maindomain/1.txt
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
java.nio.file.NoSuchFileException: /home/kali/tools/laoyue-1.2.5/result/maindomain/1.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at Bootstrap.CustomHelpers.getFileData(CustomHelpers.java:148)
        at Main.init(Main.java:128)
        at Main.main(Main.java:46)
java -jar ./inifile/hostscan/HostCollision.jar -ifp ./result/ip_as_domain/1.txt -hfp ./result/maindomain/1.txt -t 10 -cssc 200 &gt; ./inifile/hostscan/2024-01-30-21-51-19_host_scan.txt

报错2：
报错位置：nuclei扫描结尾
报错内容：
[INF] Using Interactsh Server: oast.site
[INF] No results found. Better luck next time!
Traceback (most recent call last):
  File "/home/kali/tools/laoyue-1.2.5/laoyue.py", line 1397, in &lt;module&gt;
    quchong_list, mgwj_list, ld_list, fs_list, host_scan_list = quchong_info_list(all_info_list)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/tools/laoyue-1.2.5/laoyue.py", line 654, in quchong_info_list
    ld_list = nuclei(file_filter_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/tools/laoyue-1.2.5/laoyue.py", line 1108, in nuclei
    result_list = open('tt.txt', 'r', encoding='utf-8').read().split('\n')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'tt.txt'

**Comment by Soufaker** [comment]
感谢提交马上修复

**Comment by Soufaker** [comment]
可以试试刚上的代码,host碰撞展示别用,取消-z参数就行了

**Comment by xxsmile123** [comment]
行的
