### ISSUE TITLE
最新版subfinder: Permission denied

### ISSUE THREAD

**Issue by zilyl** [Soufaker/laoyue#23]
查询结束了
开启subfinder子域名扫描
sh: 1: ./inifile/subfinder/subfinder: Permission denied
正在扫描域名文件: ./result/alldomain/2024-02-19-10-39-22_domians.txt
Traceback (most recent call last):
  File "/home/kali/laoyue/laoyue.py", line 1486, in <module>
    get_all_url_fo_yt()
  File "/home/kali/laoyue/laoyue.py", line 375, in get_all_url_fo_yt
    run_subfinder(domain_file)
  File "/home/kali/laoyue/laoyue.py", line 437, in run_subfinder
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './inifile/subfinder/subfinder'

**Comment by Soufaker** [comment]
chmod 777 ./inifile/subfinder/subfinder,您看看加了权限没有呢,可以在laoyue文件夹下输入./inifile/subfinder/subfinder看看是否正常使用

**Comment by zilyl** [comment]
> chmod 777 ./inifile/subfinder/subfinder,您看看加了权限没有呢,可以在laoyue文件夹下输入./inifile/subfinder/subfinder看看是否正常使用

可以了
